### ISSUE TITLE
3 phase splitted

### ISSUE THREAD

**Issue by zechnkaas** [andyboeh/esphome-amis#1]
Hi,

is it possible to display the 3 phase separately?

**Comment by andyboeh** [comment]
Unfortunately, the AMIS smart meter does not support that. See https://www.netzooe.at/Themen/Information/smart-meter/FAQ section "Welche Daten werden ausgegeben?"
So everything that's sent by the meter is parsed and supported.

**Comment by zechnkaas** [comment]
Thanks for your answer.
